"""Initial migration

Revision ID: 6ec79a2bb535
Revises: 
Create Date: 2021-04-19 15:09:01.751918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec79a2bb535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('item_code', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('datetime', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_datetime'), 'item', ['datetime'], unique=False)
    op.create_index(op.f('ix_item_item_code'), 'item', ['item_code'], unique=False)
    op.create_index(op.f('ix_item_location'), 'item', ['location'], unique=False)
    op.create_index(op.f('ix_item_type'), 'item', ['type'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_code'), 'location', ['code'], unique=True)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_code'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_item_type'), table_name='item')
    op.drop_index(op.f('ix_item_location'), table_name='item')
    op.drop_index(op.f('ix_item_item_code'), table_name='item')
    op.drop_index(op.f('ix_item_datetime'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
